version: '3'
services:
  backend:
    build: ./teste-back
    ports:
      - "8081:8080"
    depends_on:
      - db
    
    networks:
      - app-network


  frontend:
    build: ./teste-front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
