name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend image
      run: docker build -t aplicacao-teste-backend ./teste-back

    - name: Build frontend image
      run: docker build -t aplicacao-teste-frontend ./teste-front

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Run tests
      run: |
        sleep 30
        curl -f http://localhost:3000 || exit 1
        curl -f http://localhost:8081 || exit 1
